[ confusionM, perFoldRecall, perFoldPrecision, perFoldFMeasure, avgRecall, avgPrecision, avgFMeasure ] = ...
    nFold(x, y, 10, 'trainrp');
 
avgPerFoldRecall = averageResultsPerFold(perFoldRecall);
avgPerFoldPrecision = averageResultsPerFold(perFoldPrecision);
avgPerFoldFMeasure = averageResultsPerFold(perFoldFMeasure);

save deliverables2 ...
    confusionM perFoldRecall perFoldPrecision perFoldFMeasure ...
    avgRecall avgPrecision avgFMeasure ...
    avgPerFoldRecall avgPerFoldPrecision avgPerFoldFMeasure